package domain

import (
	"bankingApp/errs"
	"bankingApp/logger"
	"strconv"

	"github.com/jmoiron/sqlx"
)

type AccountRepositoryDb struct {
	client *sqlx.DB
}

func (d AccountRepositoryDb) Save(a Account) (*Account, *errs.AppError) {
	sqlInsert := "INSERT INTO accounts (customer_id, opening_date, account_type, amount, status) values (?, ?, ?, ?, ?)"

	// account_id is auto-generated field once row is inserted this ID will be generated by Database.
	result, err := d.client.Exec(sqlInsert, a.CustomerId, a.OpeningDate, a.AccountType, a.Amount, a.Status)
	if err != nil {
		logger.Error("Error while creating new account: " + err.Error())
		return nil, errs.NewUnexpectedError("Unexpected error from database")
	}
	id, err := result.LastInsertId() // last insert ID will return the value of account_id
	if err != nil {
		logger.Error("Error while getting last insert id for a new account" + err.Error())
		return nil, errs.NewUnexpectedError("Unexpected error from database")
	}
	// we need to convert this Id with type of int64 to string. Since our a.AccountId is string.
	a.AccountId = strconv.FormatInt(id, 10) // here it is converting to int64 to decimal system thats why 10 is given
	return &a, nil

}

func NewAccountRepositoryDb(dbClient *sqlx.DB) AccountRepositoryDb {
	return AccountRepositoryDb{dbClient}
}
